-- GENERATED by mobile/scripts/generate-seed.mjs from mobile/src/data/fixtures/devFixtures.ts.
-- Do not edit by hand. Regenerate with: cd mobile && npm run seed:generate
--
-- FICTIONAL development data only. Every person, office, organization,
-- election, and source is invented. For local / branch databases ONLY.
-- Never run this against a database that holds real records.

begin;

do $$
begin
  if exists (
    select 1 from public.people
    where publication_status = 'PUBLISHED' and id not in ('b199c7a8-0b7b-6503-6c07-698bc72d87f3', 'e6ca32cd-32d2-c781-77cc-44b210dd8800', '31e19420-0b2d-b664-3d82-06ba7244cd75', '72b46115-8272-a0fb-b624-405b85bab363', 'c7509707-5e67-cff6-7f1b-151f9f80e461', '7ecc43e5-ad70-0e46-bed1-11b1033bca02', 'bf09d0bd-1ea9-dd58-07c8-d22780b505ea', 'f1aff1c0-a639-5b95-2ff8-4a77415f5f86', '0c003678-fc19-ec36-63b0-b88d423a9b6a', '9a2cb0cc-19d4-8070-5d9a-7d9ef21704f3', 'd97206b8-e62a-37fa-5c51-43f2d5271455', '0a4f6dc9-cf6d-69a6-9b2e-4496ba8cc870', 'ab7757ea-7a0d-1f46-8ed5-160be25b3f2f', '03fe12cd-7725-528e-9eb3-9eb12b16fc44', 'bb6796d8-5b70-b44b-08b3-8e86edc3828b', '170907f1-9bbb-94ba-58b5-1a7ddfaee707', 'b94631ce-d95f-0613-6085-d500eea47c3b', '72ffa883-7aad-d15c-b2d7-7831f1bb50a6', '532a36fe-2c83-7ab1-ff10-2c34bcbd4681', '4fe41ec6-dccd-2972-22af-4b4650b3fb73', '37bbb0ec-169b-749b-9fe4-c810d7334190', '3d1d41c0-da14-8f80-68b0-f9d812c92d55', '7e467592-ea97-6b78-7141-5317e5a1f502', '83972b7b-e575-e101-5f24-6d64d1fd1478', '7b8d9d22-f18f-b610-7e54-6f252dae3f5b', '90b2bc18-2984-023f-f3a1-5a2d9fbaad3c', 'd414e2c1-fa44-57c6-0c32-625b3c473157', '72471dd2-a0fc-af32-6bb6-7069f84ea52c', '7b3dfc1a-2348-247e-63f5-c89f407eb3a6', '68263b64-db22-9d2f-8529-756e600b7ea3', 'ea83bf1b-2265-726d-d2ec-9ef5a2530759', '760c1701-af27-0093-717c-7ab8741f6094', '1e88e201-08dd-7033-ae73-13e6f25c7f1c', 'a76df69a-1b75-7db6-b79f-b4446f72e766', '77319ab0-b8a5-1c8b-c8fb-d080caeeb07c', '70faf7b3-e082-30b3-db60-d094b05834e8', '9ce3a595-52e9-f996-4ac5-78051f598753', 'b0e56e60-769c-eb74-d2e2-a25cfae861ca', 'bcb51c2b-588e-98b6-7b5b-1ed5745ce170', 'b5f2a4d8-9407-cfe7-ef0a-b21d7120607e', 'bf6f9cf3-b621-6090-85e3-2be3c4c80a39', 'eab2eb62-04d8-94b3-f118-f81d67d91e41')
  ) then
    raise exception 'Refusing to seed: this database already holds non-fixture published people';
  end if;
end
$$;

select set_config('gnj.change_reason', 'Development seed: fictional fixtures', true);

-- people
insert into public.people (id, first_name, middle_name, last_name, suffix, preferred_name, birth_date, photo_asset_id) values
  ('b199c7a8-0b7b-6503-6c07-698bc72d87f3', 'Juan', null, 'Dela Cruz', null, null, '1980-06-12', null),
  ('e6ca32cd-32d2-c781-77cc-44b210dd8800', 'Maria', 'Luntian', 'Makabayan', null, null, null, null),
  ('31e19420-0b2d-b664-3d82-06ba7244cd75', 'Pedro', null, 'Santos', 'Jr.', null, null, null);

-- elections
insert into public.elections (id, name, election_date, country_code, status) values
  ('72b46115-8272-a0fb-b624-405b85bab363', 'Halimbawa City Local Election 2027 (fictional)', '2027-05-10', 'PH', 'UPCOMING');

-- offices
insert into public.offices (id, name, level, jurisdiction_id) values
  ('c7509707-5e67-cff6-7f1b-151f9f80e461', 'Mayor, City of Halimbawa (fictional)', 'CITY', 'jurisdiction-halimbawa-city'),
  ('7ecc43e5-ad70-0e46-bed1-11b1033bca02', 'City Councilor, City of Halimbawa (fictional)', 'CITY', 'jurisdiction-halimbawa-city'),
  ('bf09d0bd-1ea9-dd58-07c8-d22780b505ea', 'Punong Barangay, Barangay Uno, Halimbawa (fictional)', 'BARANGAY', 'jurisdiction-barangay-uno');

-- political_organizations
insert into public.political_organizations (id, name, abbreviation, organization_type) values
  ('f1aff1c0-a639-5b95-2ff8-4a77415f5f86', 'Partido Halimbawa (fictional)', 'PHal', 'POLITICAL_PARTY'),
  ('0c003678-fc19-ec36-63b0-b88d423a9b6a', 'Samahang Kathang-Isip (fictional)', 'SKI', 'OTHER');

-- sources
insert into public.sources (id, title, publisher, url, document_identifier, source_type, published_at, retrieved_at, archived_url) values
  ('9a2cb0cc-19d4-8070-5d9a-7d9ef21704f3', 'Certificate of Candidacy for Mayor: Maria L. Makabayan (fictional)', 'Halimbawa City Election Office (fictional)', 'https://example.org/gabay-ni-juan-fixtures/election-office/coc/maria-makabayan', 'HCEO-COC-2027-0041 (fictional)', 'OFFICIAL_GOVERNMENT', '2026-08-15', '2026-09-30', null),
  ('d97206b8-e62a-37fa-5c51-43f2d5271455', 'Certified List of Candidates, Halimbawa City 2027 (fictional)', 'Halimbawa City Election Office (fictional)', 'https://example.org/gabay-ni-juan-fixtures/election-office/certified-list-2027', null, 'OFFICIAL_GOVERNMENT', '2026-09-15', '2026-09-30', null),
  ('0a4f6dc9-cf6d-69a6-9b2e-4496ba8cc870', 'Roster of Elected City Officials 2022–2025 (fictional)', 'Halimbawa City Secretary''s Office (fictional)', 'https://example.org/gabay-ni-juan-fixtures/city-secretary/roster-2022', null, 'OFFICIAL_GOVERNMENT', '2022-07-05', '2026-09-30', 'https://example.org/gabay-ni-juan-fixtures/archive/city-secretary/roster-2022'),
  ('ab7757ea-7a0d-1f46-8ed5-160be25b3f2f', 'Barangay Uno Officials, 2018–2023 (fictional)', 'Barangay Uno Secretariat (fictional)', 'https://example.org/gabay-ni-juan-fixtures/barangay-uno/officials-2018', null, 'OFFICIAL_GOVERNMENT', '2018-07-02', '2026-09-30', null),
  ('03fe12cd-7725-528e-9eb3-9eb12b16fc44', 'Barangay Uno turns over leadership after five-year term (fictional)', 'Pahayagang Halimbawa (fictional newspaper)', 'https://example.org/gabay-ni-juan-fixtures/pahayagang-halimbawa/barangay-uno-turnover', null, 'NEWS', '2023-12-01', '2026-09-30', null),
  ('bb6796d8-5b70-b44b-08b3-8e86edc3828b', 'Councilor Santos weighing mayoral bid, sources say (fictional)', 'Pahayagang Halimbawa (fictional newspaper)', 'https://example.org/gabay-ni-juan-fixtures/pahayagang-halimbawa/santos-weighing-bid', null, 'NEWS', '2026-09-20', '2026-09-30', null),
  ('170907f1-9bbb-94ba-58b5-1a7ddfaee707', 'New city council sworn in (fictional)', 'Balitang Kathang-Isip (fictional newspaper)', 'https://example.org/gabay-ni-juan-fixtures/balitang-kathang-isip/council-sworn-in', null, 'NEWS', '2022-07-02', '2026-09-30', null),
  ('b94631ce-d95f-0613-6085-d500eea47c3b', 'Maria Makabayan for Mayor: Platform (fictional)', 'Maria Makabayan campaign (fictional)', 'https://example.org/gabay-ni-juan-fixtures/campaigns/maria-makabayan/platform', null, 'OFFICIAL_CANDIDATE', '2026-08-20', '2026-09-30', null),
  ('72ffa883-7aad-d15c-b2d7-7831f1bb50a6', 'About Juan Dela Cruz (fictional campaign page)', 'Juan Dela Cruz campaign (fictional)', 'https://example.org/gabay-ni-juan-fixtures/campaigns/juan-dela-cruz/about', null, 'OFFICIAL_CANDIDATE', '2026-09-02', '2026-09-30', null),
  ('532a36fe-2c83-7ab1-ff10-2c34bcbd4681', 'Samahang Kathang-Isip membership roster, 2019 (fictional)', 'Samahang Kathang-Isip (fictional)', null, 'SKI-ROSTER-2019 (fictional)', 'OTHER', '2019-03-01', '2026-09-30', null);

-- election_participations
insert into public.election_participations (id, person_id, election_id, office_id, ballot_number, status, effective_from, effective_to) values
  ('4fe41ec6-dccd-2972-22af-4b4650b3fb73', 'e6ca32cd-32d2-c781-77cc-44b210dd8800', '72b46115-8272-a0fb-b624-405b85bab363', 'c7509707-5e67-cff6-7f1b-151f9f80e461', null, 'FILED_COC', '2026-08-15', null),
  ('37bbb0ec-169b-749b-9fe4-c810d7334190', 'b199c7a8-0b7b-6503-6c07-698bc72d87f3', '72b46115-8272-a0fb-b624-405b85bab363', 'c7509707-5e67-cff6-7f1b-151f9f80e461', '2', 'OFFICIAL_CANDIDATE', '2026-09-15', null),
  ('3d1d41c0-da14-8f80-68b0-f9d812c92d55', '31e19420-0b2d-b664-3d82-06ba7244cd75', '72b46115-8272-a0fb-b624-405b85bab363', 'c7509707-5e67-cff6-7f1b-151f9f80e461', null, 'POTENTIAL_ASPIRANT', '2026-09-20', null);

-- office_terms
insert into public.office_terms (id, person_id, office_id, start_date, end_date, status) values
  ('7e467592-ea97-6b78-7141-5317e5a1f502', 'e6ca32cd-32d2-c781-77cc-44b210dd8800', '7ecc43e5-ad70-0e46-bed1-11b1033bca02', '2022-06-30', '2025-06-30', 'ELECTED'),
  ('83972b7b-e575-e101-5f24-6d64d1fd1478', 'b199c7a8-0b7b-6503-6c07-698bc72d87f3', 'bf09d0bd-1ea9-dd58-07c8-d22780b505ea', '2018-06-30', '2023-11-30', 'ELECTED'),
  ('7b8d9d22-f18f-b610-7e54-6f252dae3f5b', '31e19420-0b2d-b664-3d82-06ba7244cd75', '7ecc43e5-ad70-0e46-bed1-11b1033bca02', '2022-06-30', null, 'ELECTED');

-- affiliation_records
insert into public.affiliation_records (id, person_id, organization_id, affiliation_type, start_date, end_date) values
  ('90b2bc18-2984-023f-f3a1-5a2d9fbaad3c', 'e6ca32cd-32d2-c781-77cc-44b210dd8800', 'f1aff1c0-a639-5b95-2ff8-4a77415f5f86', 'CANDIDATE', '2026-08-15', null),
  ('d414e2c1-fa44-57c6-0c32-625b3c473157', 'b199c7a8-0b7b-6503-6c07-698bc72d87f3', '0c003678-fc19-ec36-63b0-b88d423a9b6a', 'MEMBER', '2016-01-10', null);

-- education_records
insert into public.education_records (id, person_id, institution, program, credential, start_date, end_date) values
  ('72471dd2-a0fc-af32-6bb6-7069f84ea52c', 'b199c7a8-0b7b-6503-6c07-698bc72d87f3', 'Pamantasan ng Halimbawa (fictional)', 'Civil Engineering', 'Bachelor of Science', null, '2002-04-15');

-- policy_position_records
insert into public.policy_position_records (id, person_id, topic, position_text, attribution_type, stated_at) values
  ('7b3dfc1a-2348-247e-63f5-c89f407eb3a6', 'e6ca32cd-32d2-c781-77cc-44b210dd8800', 'Public transport', 'Proposes dedicated bus lanes on Halimbawa Avenue.', 'OFFICIAL_PLATFORM', '2026-08-20'),
  ('68263b64-db22-9d2f-8529-756e600b7ea3', 'b199c7a8-0b7b-6503-6c07-698bc72d87f3', 'Flood control', 'Stated that drainage upgrades in low-lying barangays would be a priority.', 'SPEECH', '2026-09-02');

-- claims
insert into public.claims (id, subject_person_id, subject_record_type, subject_record_id, claim_type, statement, effective_from, effective_to, verification_status, last_reviewed_at) values
  ('ea83bf1b-2265-726d-d2ec-9ef5a2530759', 'e6ca32cd-32d2-c781-77cc-44b210dd8800', 'ELECTION_PARTICIPATION', '4fe41ec6-dccd-2972-22af-4b4650b3fb73', 'CANDIDACY_STATUS', 'Filed a certificate of candidacy for Mayor on 15 August 2026.', '2026-08-15', null, 'PRIMARY_SOURCE', '2026-10-01'),
  ('760c1701-af27-0093-717c-7ab8741f6094', 'e6ca32cd-32d2-c781-77cc-44b210dd8800', 'OFFICE_TERM', '7e467592-ea97-6b78-7141-5317e5a1f502', 'OFFICE_TERM', 'Served as City Councilor from 30 June 2022 to 30 June 2025.', '2022-06-30', '2025-06-30', 'DISPUTED', '2026-10-01'),
  ('1e88e201-08dd-7033-ae73-13e6f25c7f1c', 'e6ca32cd-32d2-c781-77cc-44b210dd8800', 'AFFILIATION', '90b2bc18-2984-023f-f3a1-5a2d9fbaad3c', 'AFFILIATION', 'Partido Halimbawa is named as her party on her certificate of candidacy.', '2026-08-15', null, 'PRIMARY_SOURCE', '2026-10-01'),
  ('a76df69a-1b75-7db6-b79f-b4446f72e766', 'e6ca32cd-32d2-c781-77cc-44b210dd8800', 'POLICY_POSITION', '7b3dfc1a-2348-247e-63f5-c89f407eb3a6', 'POLICY_POSITION', 'Her published campaign platform proposes dedicated bus lanes on Halimbawa Avenue.', '2026-08-20', null, 'SELF_DECLARED', '2026-10-01'),
  ('77319ab0-b8a5-1c8b-c8fb-d080caeeb07c', 'b199c7a8-0b7b-6503-6c07-698bc72d87f3', 'PERSON', 'b199c7a8-0b7b-6503-6c07-698bc72d87f3', 'BIRTH_DATE', 'Born on 12 June 1980, according to his campaign page.', null, null, 'SELF_DECLARED', '2026-10-01'),
  ('70faf7b3-e082-30b3-db60-d094b05834e8', 'b199c7a8-0b7b-6503-6c07-698bc72d87f3', 'ELECTION_PARTICIPATION', '37bbb0ec-169b-749b-9fe4-c810d7334190', 'CANDIDACY_STATUS', 'Listed as a candidate for Mayor, ballot number 2, on the certified list of candidates.', '2026-09-15', null, 'PRIMARY_SOURCE', '2026-10-01'),
  ('9ce3a595-52e9-f996-4ac5-78051f598753', 'b199c7a8-0b7b-6503-6c07-698bc72d87f3', 'OFFICE_TERM', '83972b7b-e575-e101-5f24-6d64d1fd1478', 'OFFICE_TERM', 'Served as Punong Barangay of Barangay Uno from 30 June 2018 to 30 November 2023.', '2018-06-30', '2023-11-30', 'CORROBORATED', '2026-10-01'),
  ('b0e56e60-769c-eb74-d2e2-a25cfae861ca', 'b199c7a8-0b7b-6503-6c07-698bc72d87f3', 'AFFILIATION', 'd414e2c1-fa44-57c6-0c32-625b3c473157', 'AFFILIATION', 'Listed as a member in Samahang Kathang-Isip''s 2019 roster. No later roster has been located.', '2016-01-10', null, 'OUTDATED', '2026-10-01'),
  ('bcb51c2b-588e-98b6-7b5b-1ed5745ce170', 'b199c7a8-0b7b-6503-6c07-698bc72d87f3', 'EDUCATION', '72471dd2-a0fc-af32-6bb6-7069f84ea52c', 'EDUCATION', 'States he completed a BS in Civil Engineering at Pamantasan ng Halimbawa in 2002.', null, null, 'SELF_DECLARED', '2026-10-01'),
  ('b5f2a4d8-9407-cfe7-ef0a-b21d7120607e', 'b199c7a8-0b7b-6503-6c07-698bc72d87f3', 'POLICY_POSITION', '68263b64-db22-9d2f-8529-756e600b7ea3', 'POLICY_POSITION', 'In a 2 September 2026 speech, he stated that drainage upgrades in low-lying barangays would be a priority.', '2026-09-02', null, 'SELF_DECLARED', '2026-10-01'),
  ('bf6f9cf3-b621-6090-85e3-2be3c4c80a39', '31e19420-0b2d-b664-3d82-06ba7244cd75', 'ELECTION_PARTICIPATION', '3d1d41c0-da14-8f80-68b0-f9d812c92d55', 'CANDIDACY_STATUS', 'Reported as considering a run for Mayor. No certificate of candidacy has been located.', '2026-09-20', null, 'REPORTED', '2026-10-01'),
  ('eab2eb62-04d8-94b3-f118-f81d67d91e41', '31e19420-0b2d-b664-3d82-06ba7244cd75', 'OFFICE_TERM', '7b8d9d22-f18f-b610-7e54-6f252dae3f5b', 'OFFICE_TERM', 'Described as a City Councilor since 30 June 2022. No document has been attached yet.', '2022-06-30', null, 'UNVERIFIED', '2026-10-01');

-- claim_evidence
insert into public.claim_evidence (claim_id, source_id, supports, note) values
  ('ea83bf1b-2265-726d-d2ec-9ef5a2530759', '9a2cb0cc-19d4-8070-5d9a-7d9ef21704f3', true, null),
  ('760c1701-af27-0093-717c-7ab8741f6094', '0a4f6dc9-cf6d-69a6-9b2e-4496ba8cc870', true, 'Lists the term as 30 June 2022 to 30 June 2025.'),
  ('760c1701-af27-0093-717c-7ab8741f6094', '170907f1-9bbb-94ba-58b5-1a7ddfaee707', false, 'Reports that the council was sworn in on 1 July 2022.'),
  ('1e88e201-08dd-7033-ae73-13e6f25c7f1c', '9a2cb0cc-19d4-8070-5d9a-7d9ef21704f3', true, 'Party field of the certificate.'),
  ('a76df69a-1b75-7db6-b79f-b4446f72e766', 'b94631ce-d95f-0613-6085-d500eea47c3b', true, null),
  ('77319ab0-b8a5-1c8b-c8fb-d080caeeb07c', '72ffa883-7aad-d15c-b2d7-7831f1bb50a6', true, null),
  ('70faf7b3-e082-30b3-db60-d094b05834e8', 'd97206b8-e62a-37fa-5c51-43f2d5271455', true, null),
  ('9ce3a595-52e9-f996-4ac5-78051f598753', 'ab7757ea-7a0d-1f46-8ed5-160be25b3f2f', true, null),
  ('9ce3a595-52e9-f996-4ac5-78051f598753', '03fe12cd-7725-528e-9eb3-9eb12b16fc44', true, 'Reports the end of the term in November 2023.'),
  ('b0e56e60-769c-eb74-d2e2-a25cfae861ca', '532a36fe-2c83-7ab1-ff10-2c34bcbd4681', true, 'Roster dated 2019; current membership is not documented.'),
  ('bcb51c2b-588e-98b6-7b5b-1ed5745ce170', '72ffa883-7aad-d15c-b2d7-7831f1bb50a6', true, null),
  ('b5f2a4d8-9407-cfe7-ef0a-b21d7120607e', '72ffa883-7aad-d15c-b2d7-7831f1bb50a6', true, 'Speech transcript published on the campaign page.'),
  ('bf6f9cf3-b621-6090-85e3-2be3c4c80a39', 'bb6796d8-5b70-b44b-08b3-8e86edc3828b', true, 'Based on unnamed sources; no filing found.');

-- Publish in dependency order (triggers enforce this order).
update public.people set publication_status = 'PUBLISHED' where id in ('b199c7a8-0b7b-6503-6c07-698bc72d87f3', 'e6ca32cd-32d2-c781-77cc-44b210dd8800', '31e19420-0b2d-b664-3d82-06ba7244cd75');
update public.elections set publication_status = 'PUBLISHED' where id in ('72b46115-8272-a0fb-b624-405b85bab363');
update public.offices set publication_status = 'PUBLISHED' where id in ('c7509707-5e67-cff6-7f1b-151f9f80e461', '7ecc43e5-ad70-0e46-bed1-11b1033bca02', 'bf09d0bd-1ea9-dd58-07c8-d22780b505ea');
update public.political_organizations set publication_status = 'PUBLISHED' where id in ('f1aff1c0-a639-5b95-2ff8-4a77415f5f86', '0c003678-fc19-ec36-63b0-b88d423a9b6a');
update public.sources set publication_status = 'PUBLISHED' where id in ('9a2cb0cc-19d4-8070-5d9a-7d9ef21704f3', 'd97206b8-e62a-37fa-5c51-43f2d5271455', '0a4f6dc9-cf6d-69a6-9b2e-4496ba8cc870', 'ab7757ea-7a0d-1f46-8ed5-160be25b3f2f', '03fe12cd-7725-528e-9eb3-9eb12b16fc44', 'bb6796d8-5b70-b44b-08b3-8e86edc3828b', '170907f1-9bbb-94ba-58b5-1a7ddfaee707', 'b94631ce-d95f-0613-6085-d500eea47c3b', '72ffa883-7aad-d15c-b2d7-7831f1bb50a6', '532a36fe-2c83-7ab1-ff10-2c34bcbd4681');
update public.election_participations set publication_status = 'PUBLISHED' where id in ('4fe41ec6-dccd-2972-22af-4b4650b3fb73', '37bbb0ec-169b-749b-9fe4-c810d7334190', '3d1d41c0-da14-8f80-68b0-f9d812c92d55');
update public.office_terms set publication_status = 'PUBLISHED' where id in ('7e467592-ea97-6b78-7141-5317e5a1f502', '83972b7b-e575-e101-5f24-6d64d1fd1478', '7b8d9d22-f18f-b610-7e54-6f252dae3f5b');
update public.affiliation_records set publication_status = 'PUBLISHED' where id in ('90b2bc18-2984-023f-f3a1-5a2d9fbaad3c', 'd414e2c1-fa44-57c6-0c32-625b3c473157');
update public.education_records set publication_status = 'PUBLISHED' where id in ('72471dd2-a0fc-af32-6bb6-7069f84ea52c');
update public.policy_position_records set publication_status = 'PUBLISHED' where id in ('7b3dfc1a-2348-247e-63f5-c89f407eb3a6', '68263b64-db22-9d2f-8529-756e600b7ea3');
update public.claims set publication_status = 'PUBLISHED' where id in ('ea83bf1b-2265-726d-d2ec-9ef5a2530759', '760c1701-af27-0093-717c-7ab8741f6094', '1e88e201-08dd-7033-ae73-13e6f25c7f1c', 'a76df69a-1b75-7db6-b79f-b4446f72e766', '77319ab0-b8a5-1c8b-c8fb-d080caeeb07c', '70faf7b3-e082-30b3-db60-d094b05834e8', '9ce3a595-52e9-f996-4ac5-78051f598753', 'b0e56e60-769c-eb74-d2e2-a25cfae861ca', 'bcb51c2b-588e-98b6-7b5b-1ed5745ce170', 'b5f2a4d8-9407-cfe7-ef0a-b21d7120607e', 'bf6f9cf3-b621-6090-85e3-2be3c4c80a39', 'eab2eb62-04d8-94b3-f118-f81d67d91e41');

commit;
