#!/usr/bin/env node
/**
 * Generates ../supabase/seed.sql from the FICTIONAL development fixtures in
 * src/data/fixtures/devFixtures.ts, so the database seed and the in-app mock
 * data never drift apart.
 *
 * Usage (Node >= 22.18 / 23.6 for TypeScript type stripping):
 *   npm run seed:generate
 *
 * Fixture slugs ("person-juan-dela-cruz") become deterministic UUIDs.
 */
import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { devFixtureTables } from '../src/data/fixtures/devFixtures.ts';

const here = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(here, '../../supabase/seed.sql');

const ID_COLUMNS = new Set([
  'id',
  'person_id',
  'election_id',
  'office_id',
  'organization_id',
  'subject_person_id',
  'subject_record_id',
  'claim_id',
  'source_id',
]);

/** Insert order respects foreign keys; claims are inserted before their evidence. */
const INSERT_ORDER = [
  'people',
  'elections',
  'offices',
  'political_organizations',
  'sources',
  'election_participations',
  'office_terms',
  'affiliation_records',
  'education_records',
  'award_records',
  'policy_position_records',
  'claims',
  'claim_evidence',
];

/** Publish order: everything a row references must be published first. */
const PUBLISH_ORDER = INSERT_ORDER.filter((table) => table !== 'claim_evidence');

export function fixtureUuid(slug) {
  const hex = createHash('md5').update(`gabay-ni-juan-fixture:${slug}`).digest('hex');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20, 32)}`;
}

function literal(column, value) {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return String(value);
  const text = ID_COLUMNS.has(column) ? fixtureUuid(value) : value;
  return `'${String(text).replace(/'/g, "''")}'`;
}

function insertStatement(table, rows) {
  const columns = [...new Set(rows.flatMap((row) => Object.keys(row)))];
  const values = rows.map(
    (row) => `  (${columns.map((column) => literal(column, row[column])).join(', ')})`,
  );
  return `insert into public.${table} (${columns.join(', ')}) values\n${values.join(',\n')};`;
}

const allFixtureIds = [];
const body = [];

for (const table of INSERT_ORDER) {
  const rows = devFixtureTables[table] ?? [];
  if (rows.length === 0) continue;
  body.push(`-- ${table}`, insertStatement(table, rows), '');
  if (table !== 'claim_evidence') {
    allFixtureIds.push(...rows.map((row) => fixtureUuid(row.id)));
  }
}

body.push('-- Publish in dependency order (triggers enforce this order).');
for (const table of PUBLISH_ORDER) {
  const rows = devFixtureTables[table] ?? [];
  if (rows.length === 0) continue;
  const ids = rows.map((row) => `'${fixtureUuid(row.id)}'`).join(', ');
  body.push(`update public.${table} set publication_status = 'PUBLISHED' where id in (${ids});`);
}

const idList = allFixtureIds.map((id) => `'${id}'`).join(', ');
const sql = `-- GENERATED by mobile/scripts/generate-seed.mjs from mobile/src/data/fixtures/devFixtures.ts.
-- Do not edit by hand. Regenerate with: cd mobile && npm run seed:generate
--
-- FICTIONAL development data only. Every person, office, organization,
-- election, and source is invented. For local / branch databases ONLY.
-- Never run this against a database that holds real records.

begin;

do $$
begin
  if exists (
    select 1 from public.people
    where publication_status = 'PUBLISHED' and id not in (${idList})
  ) then
    raise exception 'Refusing to seed: this database already holds non-fixture published people';
  end if;
end
$$;

select set_config('gnj.change_reason', 'Development seed: fictional fixtures', true);

${body.join('\n')}

commit;
`;

writeFileSync(outFile, sql);
console.log(`Wrote ${outFile}`);
